# Generated by Django 3.1.5 on 2021-03-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20210321_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-pk'], 'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(default=1, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
