# Generated by Django 3.1.5 on 2021-03-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20210321_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
