# Generated by Django 3.1.5 on 2021-03-22 04:30

from django.db import migrations, models
import pets.models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20210321_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=pets.models.upload_location),
        ),
    ]
